// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbtllvbbeaqfjpuzlxpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpidGxsdmJiZWFxZmpwdXpseHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjQyMDAsImV4cCI6MjA2MDY0MDIwMH0.5P-btz_tqCfENfWHxSieLhw1_F2igtc7245yaN5QyT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);